package site.ymango.user.enums;

public enum PerferMbti {
  OOOO, OOOJ, OOOP, OOFO, OOFJ, OOFP, OONO, OONJ, OONP, OSOO, OSOJ, OSOP, OSFO, OSFJ, OSFP, OSNO, OSNJ, OSNP, ONOO, ONOJ, ONOP, ONFO, ONFJ, ONFP, ONNO, ONNJ, ONNP, IOOO, IOOJ, IOOP, IOFO, IOFJ, IOFP, IONO, IONJ, IONP, ISOO, ISOJ, ISOP, ISFO, ISFJ, ISFP, ISNO, ISNJ, ISNP, INOO, INOJ, INOP, INFO, INFJ, INFP, INNO, INNJ, INNP, EOOO, EOOJ, EOOP, EOFO, EOFJ, EOFP, EONO, EONJ, EONP, ESOO, ESOJ, ESOP, ESFO, ESFJ, ESFP, ESNO, ESNJ, ESNP, ENOO, ENOJ, ENOP, ENFO, ENFJ, ENFP, ENNO, ENNJ, ENNP
}
